// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // `.env.example` ships SHADOW_DATABASE_URL="" and Prisma rejects an empty
    // string with P1013, so coerce empty to undefined. The local `prisma dev`
    // server carries its own shadow database inside the connection string and
    // needs nothing here; Neon needs a real value.
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"] || undefined,
  },
});
